Repositoryのテストを追加
aapaca/aapaca_backend pull request #19
Opened 2021-01-13 09:31 UTC by marblet

- album_repository_test.go、artist_repository_test.go、song_repository_test.goにRepositoryのテストを記述
- Github Actions上でmysqlを起動してテストできるように諸々を更新

2021-01-27 09:55 UTC, ur0n requested changes

2021-01-27 09:55 UTC, ur0n commented on src/app/test/infrastructure/mysqlhandler.go
> +	// dbPath := "aapaca_user:passwd@tcp(192.168.99.100:3306)/aapaca?parseTime=true"
これは消し忘れ？

2021-01-27 09:55 UTC, ur0n commented on src/app/interfaces/database/album_repository_test.go
> +	err := deleteAllRecords(sqlHandler)
事前にinsertする処理とかdeleteする処理ってテストケースごとにbefore/after ALLとかでやった方がよさそう！
https://golang.org/pkg/testing/#hdr-Main

2021-01-27 09:56 UTC, ur0n commented
毎度遅くなってすみません 🙇‍♂️ 
めっちゃリマインドしてくれると助かる..

2021-02-10 04:51 UTC, marblet commented
テストを全体的に更新しました

2021-02-14 03:12 UTC, ur0n approved these changes

2021-02-14 03:30 UTC, merged