Feature/add mysql setting
aapaca/aapaca_backend pull request #3
Opened 2020-07-20 13:16 UTC by marblet

- Dockerfileとdocker-compose.ymlの設定
- DB table初期化コードの実装

2020-07-21 11:31 UTC, qiringji approved these changes
自分が見れる範囲ではLGTM
Dockerまわりウーロンに確認して欲しい

後コメントしたところウーロンの意見欲しい

2020-07-21 11:31 UTC, qiringji commented on mysql/docker/mysql/conf.d/my.cnf
> +general-log=1　                  # 実行したクエリの全ての履歴が記録される（defaultではOFFになっているらしい）
これは将来的にはどうするのがログいつまで保存するのかとか考えたほうがええんかな

2020-07-21 11:31 UTC, qiringji commented on mysql/docker/mysql/initdb.d/contains.sql
> +CREATE TABLE aapaca.contains (
こうやってみるとcontains広い気がする
ウーロンの意見聞きたし

2020-07-24 06:03 UTC, ur0n requested changes

2020-07-24 06:03 UTC, ur0n commented on mysql/docker/mysql/conf.d/my.cnf
> +general-log=1　                  # 実行したクエリの全ての履歴が記録される（defaultではOFFになっているらしい）
基本的にoffで大丈夫そう

2020-07-24 06:03 UTC, ur0n commented on mysql/docker/mysql/initdb.d/albums.sql
> +);
artistsへの外部キー制約あった方がよさそう

2020-07-24 06:03 UTC, ur0n commented on mysql/docker/mysql/initdb.d/contains.sql
> +CREATE TABLE aapaca.contains (
他にalbumとsongの関係にいい名前が思いつかない。。。
他には、`has` とか `belongs to` とか？？

2020-07-24 06:03 UTC, ur0n commented on mysql/docker/mysql/initdb.d/contains.sql
> +    PRIMARY KEY (id)
本当にごめんだけど前に中間テーブルにもid欲しいって行ったけど、そうすると意味が同じなのにidだけ違うデータ入っちゃうわ。　
https://tokyotechjazz.slack.com/archives/CE784JRQ8/p1594689499011800

|  id |  album_id  |  song_id  |
|---|---|---|
|  1 | 2  | 3  |
|  2 | 1  | 3  |
|  3  | 2  | 3  |

↑ 1行目と3行目は意味は同じだけど、違うデータになってしまう。
中間テーブルに他の意味があって中間テーブルを他のテーブルで参照する場合にはidはあっていいと思うけどそれ以外はいらなそう。

2020-07-24 06:03 UTC, ur0n commented on mysql/docker/mysql/initdb.d/is_a_member_of.sql
> +    PRIMARY KEY (id)
上に同じ

2020-07-24 06:03 UTC, ur0n commented on mysql/docker/mysql/initdb.d/is_also_known_as.sql
> +    PRIMARY KEY (id)
上に同じ

2020-07-24 06:03 UTC, ur0n commented on mysql/docker/mysql/initdb.d/contains.sql
> +    PRIMARY KEY (id)
あと外部キー制約も！

2020-07-24 06:03 UTC, ur0n commented on mysql/docker/mysql/initdb.d/performs.sql
> +);
外部キー制約ほしそう

2020-07-24 06:03 UTC, ur0n commented on mysql/docker/mysql/initdb.d/songs.sql
> +);
外部キー制約ほしそう

2020-07-24 11:59 UTC, marblet commented
修正しました！
- ファイルの再統合
  albums, artists, occupations, songsを1_main_tables.sql、それ以外を2_junction_tables.sqlへまとめました。dbを初期化する際の生成順序を決めるために、ファイル名に1とか2とかつけています。
- songs, albumsのprimary_artist_idに外部キー制約を追加
- 中間テーブルたちのidを削除、外部キー制約を追加

2020-07-25 09:11 UTC, qiringji commented
ur0nのコメントが反映されてそう
ファイルの粒度はどっちでもいいかなって思いますた

2020-07-25 09:13 UTC, ur0n approved these changes

2020-07-25 09:24 UTC, merged